#!/bin/bash


# fitsumbelay@gmail.com
# created : 19 April 2011
# updated : 21 April 2011


# PROCESS TODO 
# 
# check shell diffs
# curl AIFF to Apache/LAME
# Trig PHP -> LAME
# 	LAME processes, renames, moves to final destination
# confirm file creation; TODO - confirm  steps, playback option for local 
# Trig PHP -> Tweet

# inputs:
# HTML element 
# check result of URL?=xxx 
# script to update ln from some file mod date
# upload mp3 somewhere


# UI TODO
#
# OSX UI


# VARS
_tn=tmpFile.aiff
_dn=`dirname "$1"`
_fn=`basename "$1"`
_ext=".txt"
_fn=${_fn:0:$((${#_fn}-${#_ext}))}


# MAIN DIRECTIVES
say -o $_dn/$_tn -f $1
lame  --silent $_dn/$_tn $_dn/$_fn.mp3  --tt $_fn --ta 'JustSayen(TM)' --ti coverart.jpg



#CLEAN UP DIRECTIVE
rm $_dn/$_tn 


