#!/bin/bash


# fitsumbelay@gmail.com
# created : 19 April 2011
# updated : 21 April 2011

# VARS
_tn=tmpFile.aiff
_dn=`dirname "$1"`
_fn=`basename "$1"`
_ext=".txt"
_fn=${_fn:0:$((${#_fn}-${#_ext}))}


# MAIN DIRECTIVES
say -o $_dn/$_tn -f $1
lame --silent $_dn/$_tn $_dn/$_fn.mp3 --ti me.png  --tt $_fn --ta 'JustSayen(TM)'


#CLEAN UP DIRECTIVE
rm $_dn/$_tn 


